GET http://localhost:3008/
###
GET http://localhost:3010/players/
###
GET http://localhost:3010/player/7
###
POST http://localhost:3010/players/
Content-Type: application/json

{   
  "playerId":78,
  "playerName":"rohit",
  "jerseyNumber":43,
  "role":"batsman"
}

###
PUT http://localhost:3010/player/2
Content-Type: application/json

{
  "playerId":78,
  "playerName":"rohit",
  "jerseyNumber":43,
  "role":"batsman"
}



###


DELETE  http://localhost:3001/players/3
