GET  http://localhost:4005/
###
POST http://localhost:4005/register
Content-Type: application/json

{
    "fullname": "kiran", 
    "State": "Ap", 
    "Currentlocation":"kadapa", 
    "mobile": "9654785478", 
    "email": "kiran@gmail.com"
     
}
 