GET  http://localhost:4005/
###
POST http://localhost:4005/register
Content-Type: application/json

{
    "fullname": "kiran", 
    "State": "Ap", 
    "Currentlocation":"kadapa", 
    "mobile": "9654785478", 
    "email": "kiran@gmail.com"
     
}
###
GET http://localhost:4005/alldevelopers
###
POST http://localhost:4005/resumeheding1
Content-Type: application/json

{
    "resumeheading": "saikrishna"
}
 